### ISSUE TITLE
Update `onCrossChainCall` with `zContext`

### ISSUE THREAD

**Issue by fadeev** [zeta-chain/docs#107]
```[tasklist]
### Tasks
- [ ] https://github.com/zeta-chain/example-contracts/pull/43
- [ ] https://github.com/zeta-chain/docs/pull/106
- [ ] https://github.com/zeta-chain/toolkit/pull/28
- [ ] https://github.com/zeta-chain/toolkit/pull/32
- [x] Release an updated version of `@zetachain/toolkit`
- [ ] https://github.com/zeta-chain/template/issues/22
```

Relevant: https://github.com/zeta-chain/node/pull/912

**Comment by fadeev** [comment]
@lucas-janon @andresaiello I might need your help reviewing PRs above.
