### ISSUE TITLE
Developer experience roadmap

### ISSUE THREAD

**Issue by fadeev** [zeta-chain/docs#32]
```[tasklist]
### Tasks
- [ ] https://github.com/zeta-chain/docs/issues/8
- [ ] https://github.com/zeta-chain/docs/issues/33
- [ ] https://github.com/zeta-chain/docs/issues/34
- [ ] https://github.com/zeta-chain/docs/issues/11
- [ ] https://github.com/zeta-chain/docs/issues/101
- [ ] https://github.com/zeta-chain/example-contracts/issues/14
```

**Comment by 1337-ishaan** [comment]
Hey @fadeev, I would like to assist you with this if it is open.

**Comment by fadeev** [comment]
@1337-ishaan let me know which area you want to contribute to!

**Comment by 1337-ishaan** [comment]
I can get #34 and #14 respectively, can you assign them to me?

**Comment by fadeev** [comment]
@1337-ishaan that would be a great contribution! Feel free to assign yourself to any (or both) of these issues:

https://github.com/zeta-chain/docs/issues/93
https://github.com/zeta-chain/docs/issues/95

I've recently migrated the NFT (warriors) example to templating, so that could be used as an example (not to say it was done perfectly, but still).

If you want to try adding tests, that would be great, too:

https://github.com/zeta-chain/example-contracts/issues/14

Describing your proposed solution in an issue before committing to writing the code would help us agree on the best course of action.

Really appreciate your interest in the project! 🙌

**Comment by 1337-ishaan** [comment]
I'll get both of it done, let's decide the best course of action, then can assign myself to the task.
