### ISSUE TITLE
Migrate to use templating for tutorials

### ISSUE THREAD

**Issue by fadeev** [zeta-chain/docs#34]
Right now tutorials are repetitive and contain to much code to copy/paste.

We want to improve the tutorial flow to be:

1. Clone the template
2. Run `npx hardhat omnichain` or `npx hardhad messaging` to generate the boilerplate code (these tasks are [already](https://github.com/zeta-chain/toolkit/pull/8) [implemented](https://github.com/zeta-chain/toolkit/blob/628f5a96a088681fe53e357b8d012ab448daf0e2/tasks/omni.ts)!)
3. Make some changes to the generated code to implement desired functionality

This should make tutorials 2-3 times easier and faster to follow.
```[tasklist]
### Tasks
- [ ] https://github.com/zeta-chain/docs/issues/93
- [ ] https://github.com/zeta-chain/docs/issues/94
- [ ] https://github.com/zeta-chain/docs/issues/95
- [ ] https://github.com/zeta-chain/docs/issues/96
- [ ] https://github.com/zeta-chain/docs/issues/92
- [x] https://github.com/zeta-chain/docs/issues/98
- [x] https://github.com/zeta-chain/docs/issues/99
- [ ] https://github.com/zeta-chain/docs/issues/100
```
