### ISSUE TITLE
Update ZetaHub pages

### ISSUE THREAD

**Issue by fadeev** [zeta-chain/docs#423]
```[tasklist]
### Tasks
- [ ] https://github.com/zeta-chain/docs/issues/419
- [ ] https://github.com/zeta-chain/docs/issues/422
- [ ] https://github.com/zeta-chain/docs/issues/421
- [ ] https://github.com/zeta-chain/docs/issues/420
```
