### ISSUE TITLE
Doc on using `zetacored` to setup account and broadcast transactions

### ISSUE THREAD

**Issue by fadeev** [zeta-chain/docs#64]
```[tasklist]
### Tasks
- [ ] link to https://docs.cosmos.network/main/run-node/txs
- [ ] `zetacored keys add alice (recover)`
- [ ] `zetacored tx bank send ... --node ...`
```
