### ISSUE TITLE
Update developer experience for Athens 3

### ISSUE THREAD

**Issue by fadeev** [zeta-chain/docs#8]
```[tasklist]
- [ ] https://github.com/zeta-chain/networks/issues/9
- [ ] https://github.com/zeta-chain/protocol-contracts/issues/37
- [ ] https://github.com/zeta-chain/toolkit/issues/11
- [ ] https://github.com/zeta-chain/example-contracts/issues/11
- [ ] https://github.com/zeta-chain/template/issues/12
- [ ] https://github.com/zeta-chain/docs/issues/17
```
